### ISSUE TITLE
blockchain555 - A user may open more positions than the protocol intends.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-velar-artha-judging#10]
blockchain555

Medium

# A user may open more positions than the protocol intends.

## Summary
The protocol limits a user to open `max_position` positions. However, a user can create more positions than this threshold.

## Vulnerability Detail
Let's look at `open()` of `positions.vy`.
```vyper
@external
def open(
  user      : address,
  pool      : uint256,
  long      : bool,
  collateral: uint256,
  leverage  : uint256,
  ctx       : Ctx) -> PositionState:
  self._INTERNAL()

  # Opening a position with leverage can be thought of as purchasing
  # an amplified number of tokens.
  # Longs buy base tokens with quote collateral and shorts buy quote
  # tokens with base collateral (alternatively, longs buy base and shorts
  # sell base).
  virtual_tokens: uint256 = self.MATH.quote_to_base(collateral, ctx) if long else (
                            self.MATH.base_to_quote(collateral, ctx) )
  interest      : uint256 = virtual_tokens * leverage

  pos: PositionState      = PositionState({
    id         : self.next_position_id(),
    pool       : pool,
    user       : user,
    status     : Status.OPEN,
    long       : long,
    collateral : collateral,
    leverage   : leverage,
    interest   : interest,
    entry_price: ctx.price,
    exit_price : 0,
    opened_at  : block.number,
    closed_at  : 0,

    collateral_tagged: Tokens({base: 0, quote: collateral}) if long else (
                       Tokens({base: collateral, quote: 0}) ),
    interest_tagged  : Tokens({base: interest, quote: 0}) if long else (
                       Tokens({base: 0, quote: interest}) ),
  })
  ps: PoolState = self.POOLS.lookup(pool)

@ assert Positions(self).get_nr_user_positions(user) <= MAX_POSITIONS
  assert self.PARAMS.is_legal_position(ps, pos)

@ self.insert_user_position(user, pos.id)
  return self.insert(pos)
```
As you can see above, user can open `max_position` positions.
Let's look at the scenario below.
Alice opened `max_position` positions and now is going to open another position.
She calls `open()` of `api.vy`.
But there not occurs revert and then she opens `max_positions + 1` position.
## Impact
User can open more positions than the protocol intends.

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/positions.vy#L107-L151

## Tool used
Manual Review

Manual Review

## Recommendation
Pls modify the `open()` of `positions.vy` as below
```vyper
@external
def open(
  user      : address,
  pool      : uint256,
  long      : bool,
  collateral: uint256,
  leverage  : uint256,
  ctx       : Ctx) -> PositionState:
  self._INTERNAL()

  # Opening a position with leverage can be thought of as purchasing
  # an amplified number of tokens.
  # Longs buy base tokens with quote collateral and shorts buy quote
  # tokens with base collateral (alternatively, longs buy base and shorts
  # sell base).
  virtual_tokens: uint256 = self.MATH.quote_to_base(collateral, ctx) if long else (
                            self.MATH.base_to_quote(collateral, ctx) )
  interest      : uint256 = virtual_tokens * leverage

  pos: PositionState      = PositionState({
    id         : self.next_position_id(),
    pool       : pool,
    user       : user,
    status     : Status.OPEN,
    long       : long,
    collateral : collateral,
    leverage   : leverage,
    interest   : interest,
    entry_price: ctx.price,
    exit_price : 0,
    opened_at  : block.number,
    closed_at  : 0,

    collateral_tagged: Tokens({base: 0, quote: collateral}) if long else (
                       Tokens({base: collateral, quote: 0}) ),
    interest_tagged  : Tokens({base: interest, quote: 0}) if long else (
                       Tokens({base: 0, quote: interest}) ),
  })
  ps: PoolState = self.POOLS.lookup(pool)

- assert Positions(self).get_nr_user_positions(user) <= MAX_POSITIONS
  assert self.PARAMS.is_legal_position(ps, pos)

  self.insert_user_position(user, pos.id)
+ assert Positions(self).get_nr_user_positions(user) <= MAX_POSITIONS
  return self.insert(pos)
```

**Comment by blockchain555** [comment]
Escalate
I think this is clear valid issue.

**Comment by sherlock-admin3** [comment]
> Escalate
> I think this is clear valid issue.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by sleepriverfish** [comment]
#36 is a duplicate of this issue as well.

**Comment by WangSecurity** [comment]
Do I understand correctly that it allows to open only 1 more position than `MAX_POSITIONS`?

**Comment by pashap9990** [comment]
> Do I understand correctly that it allows to open only 1 more position than `MAX_POSITIONS`?

yes

**Comment by WangSecurity** [comment]
This issue doesn't showcase medium severity issue. The user can open only 1 position more than they should and the issue doesn't show how it leads to any considerable impact. Yes, it bypasses the intended threshold, but it's not enough for medium severity:
> Breaks core contract functionality, rendering the contract useless or leading to loss of funds.

While it breaks the functionality to some extent, the contract is not rendered useless and there's no loss of funds. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [blockchain555](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/10/#issuecomment-2347403399): rejected
