### ISSUE TITLE
0xbranded - Use of block.number to represent passage of time

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-velar-artha-judging#11]
0xbranded

Medium

# Use of block.number to represent passage of time

## Summary
The use of block.number will result in inaccurate or inconsistent fee calculations, since [block times are not fixed](https://etherscan.io/chart/blocktime).

## Vulnerability Detail
block.number is used to calculate the passage of time since the last fee update in [`fees.vy`](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/fees.vy#L147).

```solidity
  new_terms: uint256   = block.number - fs.t1
... 
  borrowing_long_sum  : uint256 = self.extend(fs.borrowing_long_sum,  fs.borrowing_long,  new_terms)
  borrowing_short_sum : uint256 = self.extend(fs.borrowing_short_sum, fs.borrowing_short, new_terms)
  funding_long_sum    : uint256 = self.extend(fs.funding_long_sum,    fs.funding_long,    new_terms)
  funding_short_sum   : uint256 = self.extend(fs.funding_short_sum,   fs.funding_short,   new_terms)
```

However, there have been numerous instances of inconsistent block times, in which case block number would not be representative of the passage of time. 

Given that the protocol will be deployed on a new chain, the risk of inconsistent block times is exacerbated, as has been observed with [Canto](https://crypto.news/canto-blockchain-struggles-to-restart-following-outage/), [Solana](https://crypto.news/solana-stops-processing-transactions-sol-sinks-by-4/), and [Starknet](https://crypto.news/starknet-faces-4-hour-outage-block-production-halts/), in which cases block production was halted entirely. Additionally, the BOB chain's [development roadmap](https://docs.gobob.xyz/docs/learn/bob-stack/roadmap) introduces possible future changes (or volatility) in block time, especially in transition periods where the settlement layer is changed.

While the admin can change fee parameters in response to changing blocktimes on the BOB chain, this approach will not mitigate volatility in blocktimes, nor halts in block generation. 
## Impact
When blocktimes speed up, users will overpay fees, while if blocktimes slow down, underpayments of fees will occur. Fee payments will generally be inconsistent, and trust in the system will be eroded. In the event of a halt in block production, no funding (or borrowing) payments will be made during that time, allowing some positions to remain unliquidated for a longer period of time and depriving positions / lps of any fees.

## Tool used

Manual Review

## Recommendation
Consider changing fee calculations to use timestamps instead of block numbers, given the predictability of block.timestamp, as it also does not compromise the security of the system.

**Comment by msheikhattari** [comment]
Escalate

Can I get more context on why this was invalidated? It's not just relating to network liveness.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Can I get more context on why this was invalidated? It's not just relating to network liveness.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
As I understand, especially from the code comments, this is how the protocol intends to work, and it's intended to accrue fees based on the number of blocks passed, not based on the passed time. In that sense, changing block. number to block. timestamp is a design recommendation rather than a security issue. Hence, planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [msheikhattari](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/11/#issuecomment-2344776608): rejected

**Comment by msheikhattari** [comment]
Just for clarification, how is the line typically drawn between design recommendation and security concerns? The usage of `block.number` was problematic for a few reasons pointed out in the issue.
