### ISSUE TITLE
0x37 - Incorrect borrowing fee calculation

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-velar-artha-judging#14]
0x37

Medium

# Incorrect borrowing fee calculation

## Summary
Traders with high collateral, low leverage will pay more borrowing fee than traders with low collateral, high leverage.

## Vulnerability Detail
Traders in markets can add some leverage in order to get higher profits. LPs have to lock `collateral * leverage` value token to match this leverage position. Traders have to pay some borrowing fee for the locked token. The borrowing fee should be related with locked token amount.
The problem is that the borrowing fee is related with this position's collateral amount, not related with leverage. This could cause some positions with less locked token amount need to pay more borrowing fees.
For example:
- Alice opens one long position with 50000 USDT, 2x leverage in BTC/USDT market.
- Bob opens one long position with 10000 USDT, 20x leverage in BTC/USDT market.
- Lps have to lock more BTC tokens for Bob compared with Alice's position. However, Alice has to pay more borrowing fee because she has one higher collateral amount.

```vyper
@external
@view
def calc_fees(id: uint256) -> FeesPaid:
  pos             : PositionState = Positions(self).lookup(id)
  pool            : PoolState     = self.POOLS.lookup(pos.pool)
  # Here collateral is this position's collateral.
  fees            : SumFees       = self.FEES.calc(
@>                                    pos.pool, pos.long, pos.collateral, pos.opened_at)
```
```vyper
@external
@view
def calc(id: uint256, long: bool, collateral: uint256, opened_at: uint256) -> SumFees:
    period: Period  = self.query(id, opened_at)
    P_b   : uint256 = self.apply(collateral, period.borrowing_long) if long else (
                      self.apply(collateral, period.borrowing_short) )
```
## Impact
Trading positions with less locked interest may have to pay more borrowing fee.

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/fees.vy#L263-L274

## Tool used
Manual Review

## Recommendation
Borrowing fee should be in propotion to positions' locked interest.

**Comment by deadrosesxyz** [comment]
Escalate

Issue should be invalidated. It is a design choice to base fees on the collateral amount. Leverage positions contain higher risk anyway.

**Comment by msheikhattari** [comment]
This is not invalid. The design choices are not equivalent since LPs must lock the same reserves for less fees under this approach. While the risk of liquidation is higher for these positions, this isn't a strong enough guarantee that reserves are locked for a proportionally less period of time. It's possible for reserves to be locked for just as long, with just as much risk of profitable positions, and LPs were not compensated fairly because leverage was higher. Unless there is some way to ensure that market conditions will never trend towards one direction for a sustained period, this must be addressed by incorporating position leverage into the fee calculation also.

**Comment by WangSecurity** [comment]
One clarification, the report says:
> Alice has to pay more borrowing fee because she has one higher collateral amount

But then, it says:
> Trading positions with less locked interest may have to pay more borrowing fee.

In the example, IIUC, Bob has less locked interest, i.e. 10000 USDT, while Alice has 50000, so why Alice pays more?

**Comment by pashap9990** [comment]
DENOM: constant(uint256) = 1_000_000_000
borrowing_paid = pos.collateral * borrowing_fee / DENOM

Alice pay more because she has locked more collateral than Bob

**Comment by WangSecurity** [comment]
After rechecking, the borrowing fee is supposed to be calculated based on the collateral. Hence, this is only a design recommendation to use a more optimal formula. Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [deadrosesxyz](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/14/#issuecomment-2344328282): accepted
