### ISSUE TITLE
pseudoArtist - Liquidation is  allowed when the protocol is paused

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-velar-artha-judging#20]
pseudoArtist

High

# Liquidation is  allowed when the protocol is paused

## Summary
The protocol allows liquidation when it is paused i.e users can't open new positions but can get liquidated
## Vulnerability Detail
Althoug there is no direct functionality to pause the protocol yet there is an indirect way to pause the protocol but partially , i.e. only disallowing users from openinig new positions. Now lets see how :

In [core.open()](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L230-L268) it is opening a new position in [Position.vy](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L260) and which has a check to ensure that the position is a legal position and can be opened 
[is_legal_position](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/positions.vy#L148) now when we see this check in `params.vy` contract :

```python
@external
@view
def is_legal_position(pool: PoolState, position: PositionState) -> bool:
    min_size: bool = position.collateral >= (self.PARAMS.MIN_LONG_COLLATERAL if position.long else
                                             self.PARAMS.MIN_SHORT_COLLATERAL)
    # Max size limits are not really enforceable since users can just
    # open multiple identical positions.
    # This can be used as a pause button (set to zero to prevent new
    # positions from being opened).

    max_size: bool = position.collateral <= (self.PARAMS.MAX_LONG_COLLATERAL if position.long else
                                             self.PARAMS.MAX_SHORT_COLLATERAL)
    min_leverage: bool = position.leverage >= (self.PARAMS.MIN_LONG_LEVERAGE if position.long else
                                               self.PARAMS.MIN_SHORT_LEVERAGE)
    max_leverage: bool = position.leverage <= (self.PARAMS.MAX_LONG_LEVERAGE if position.long else
                                               self.PARAMS.MAX_SHORT_LEVERAGE)
    return min_size and max_size and min_leverage and max_leverage
```
The code comment above suggests that `MAX_LONG_COLLATERAL` can be set to 0 and so the check will not allow any new position to be opened.

While there is no direct mechanism for pausing the protocol ,there is a mechanism when `MAX_LONG_COLLATERAL` will be set to `0` and so the user can't really open new position or add to the existing position, but there is a problem with this mechanism, since there is no check in liquidation  , which allows liquidators to liquidate the positions while the protocol is indirectly paused.
## Impact
Users won't be able to get a chance to add to their position and get unfairly liquidated.
## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/params.vy#L102-L115
## Tool used

Manual Review

## Recommendation
Use a mechanism to pause the whole protocol even liquidations and close.

**Comment by PseudoArtistHacks** [comment]
Escalate
I believe this is a valid issue since when `MAX_LONG_COLLATERAL set to 0` users can't add to their position or open a new position which leaves them with no option to make their position healthy and just simply get liquidated while there is a soft pause imposed, The liquidation function doesn't have [is_legal_position](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/positions.vy#L148) check to ensure if the protocol is in soft pause state and so the positions can get liquidated without giving a chance to the position owners to improve their health

**Comment by sherlock-admin3** [comment]
> Escalate
> I believe this is a valid issue since when `MAX_LONG_COLLATERAL set to 0` users can't add to their position or open a new position which leaves them with no option to make their position healthy and just simply get liquidated while there is a soft pause imposed, The liquidation function doesn't have [is_legal_position](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/positions.vy#L148) check to ensure if the protocol is in soft pause state and so the positions can get liquidated without giving a chance to the position owners to improve their health

You've deleted an escalation for this issue.
