### ISSUE TITLE
pseudoArtist - Users won't be able to open a position when `PROTOCOL_FEE = 0`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-velar-artha-judging#21]
pseudoArtist

High

# Users won't be able to open a position when `PROTOCOL_FEE = 0`

## Summary
If the `PROTOCOL_FEE` is set to 0 which is possible then it will not let users open a position in the pool with 0 PROTOCOL_FEE
## Vulnerability Detail
The [open](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L230-L268) function in `core.vy` is used to open the position and while doing so it fetches the [static_fees/Protocol fee](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L244) which is then further transferred to the protocol from the user.

Now if we see the implementation of [static_fees function in PARAMA.vy](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/params.vy#L93-L97)

```python
@external
@view
def static_fees(collateral: uint256) -> Fee:
  fee      : uint256 = collateral / self.PARAMS.PROTOCOL_FEE
  remaining: uint256 = collateral - fee
  return Fee({x: collateral, fee: fee, remaining: remaining})
```

In the above function the fee calculation is done as   
`fee      : uint256 = collateral / self.PARAMS.PROTOCOL_FEE` 
The collateral is divided by `PROTOCOL_FEE`, now if the `PROTOCOL_FEE = 0` then the whole function will just panic revert due to division by 0 and so the whole open function will revert due to this and due to which users will not be able to open any positions in a pool with 0 `PROTOCOL_FEE`.
## Impact
users will not be able to open any positions in a pool with 0 `PROTOCOL_FEE`.
## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/params.vy#L93-L97
## Tool used

Manual Review

## Recommendation

Add a logic in `static_fees` funciton to handle 0 `PROTOCOL_FEE`.

**Comment by PseudoArtistHacks** [comment]
Escalate
Escalating to know why is this invalidated since there can be pools with 0 protocol fee.

**Comment by sherlock-admin3** [comment]
> Escalate
> Escalating to know why is this invalidated since there can be pools with 0 protocol fee.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
The admins of the protocol set the PROTOCOL_FEE variable. There are no limitations set on the admin-set variables, hence, it should remain invalid based on the following rule:
> (External) Admin trust assumptions: When a function is access restricted, only values for specific function variables mentioned in the README can be taken into account when identifying an attack path.
If no values are provided, the (external) admin is trusted to use values that will not cause any issues.
*Omitted Exception and Note since they're irrelevant here.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [PseudoArtistHacks](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/21/#issuecomment-2345305143): rejected
