### ISSUE TITLE
bareli - Precision loss

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-velar-artha-judging#7]
bareli

Medium

# Precision loss

## Summary
There are many precision loss issues in smart contracts .

## Vulnerability Detail
def utilization(reserves: uint256, interest: uint256) -> uint256:
    """
    Reserve utilization in percent (rounded down).
    """
  @>>  return 0 if (reserves == 0 or interest == 0) else (interest / (reserves / 100))

def static_fees(collateral: uint256) -> Fee:
@>  fee      : uint256 = collateral / self.PARAMS.PROTOCOL_FEE
  remaining: uint256 = collateral - fee
  return Fee({x: collateral, fee: fee, remaining: remaining})

if user-supplied collateral is less than 1000, the collateral fee will always be zero, and for an amount greater than 1000, due to precision loss, the fee will be less than expected.

def to_amount(price: uint256, volume: uint256, one1: uint256) -> uint256:
  """
  Converts unit price to value of volume at that price.
  """
@>>  return (price * volume) / one1

def from_amount(amount: uint256, price: uint256, one1: uint256) -> uint256:
  """
  Returns volume implied by price.
  """
@>>  return (amount * one1) / price

def base_to_quote(tokens: uint256, ctx: Ctx) -> uint256:
  lifted : Tokens  = self.lift(Tokens({base: tokens, quote: ctx.price}), ctx)
@>>  amt0   : uint256 = self.to_amount(lifted.quote, lifted.base, self.one(ctx))
  lowered: Tokens  = self.lower(Tokens({base: 0, quote: amt0}), ctx)
  return lowered.quote

@external
@pure
 def quote_to_base(tokens: uint256, ctx: Ctx) -> uint256:
  l1     : Tokens  = self.lift(Tokens({base: 0, quote: tokens}),    ctx)
  l2     : Tokens  = self.lift(Tokens({base: 0, quote: ctx.price}), ctx)
@>>  vol0   : uint256 = self.from_amount(l1.quote, l2.quote, self.one(ctx))
  lowered: Tokens  = self.lower(Tokens({base: vol0, quote: 0}), ctx)
  return lowered.base

there is a precision loss in converting  base_to_quote  and quote_to_base.when we convert from quote token USDT(6 decimal) to base token WBTC(8 decimal) ,there is a precision loss.

def balanced(state: Value, burn_value: uint256, ctx: Ctx) -> Tokens:
  """
 
  """
  if state.have_more_base:
    if state.base_excess_as_quote >= burn_value:
      return Tokens({base: Math(self).quote_to_base(burn_value, ctx), quote: 0})
    else:
      base1: uint256 = state.base_excess_as_base
      left : uint256 = burn_value - state.base_excess_as_quote
      quote: uint256 = left / 2
   @>>   base2: uint256 = Math(self).quote_to_base(quote, ctx)
      base : uint256 = base1 + base2
      return Tokens({base: base, quote: quote})
  else:
    if state.quote_excess_as_quote >= burn_value:
      return Tokens({base: 0, quote: burn_value})
    else:
      quote1: uint256 = state.quote_excess_as_quote
      left  : uint256 = burn_value - quote1
      quote2: uint256 = left / 2
    @>>  base  : uint256 = Math(self).quote_to_base(quote2, ctx)
      quote : uint256 = quote1 + quote2
      return Tokens({base: base, quote: quote})

there is a precision loss here.

## Impact
precision loss is happening as we may lose the fee gain.we are also losing precision  in base_to_quote also

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/params.vy#L59
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/math.vy#L53
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/math.vy#L61
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/math.vy#L127
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/math.vy#L81
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/math.vy#L73
## Tool used

Manual Review

## Recommendation

we should reduce the precision loss .

**Comment by spacegliderrrr** [comment]
Escalate

This issue is not a valid duplicate of #91. Issue is vague and does not properly showcase any Medium-severity impact.

**Comment by WangSecurity** [comment]
Agree with the escalation. There is no proof of precision loss, and the issue doesn't show if the precision is significant enough. Planning to accept and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/7/#issuecomment-2344277141): accepted
