### ISSUE TITLE
oxwhite - Failure of Liquidity Addition-Withdrawal in USDT Based Pools

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-velar-artha-judging#70]
oxwhite

Medium

# Failure of Liquidity Addition-Withdrawal in USDT Based Pools

## Summary
`mint()` or `burn()` function in core.vy may not work when USDT is used as quote token. Because it will result in invariant break, which potentially lead some issues explained below.
## Vulnerability Detail
**First Scenario** 
Liquidity can be added  via mint() function in api.vy, which makes a call to the [mint()](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L155) in core.vy. Let's look at this function:
```python
@external
def mint(
  id          : uint256,
  base_token  : address,
  quote_token : address,
  lp_token    : address,
  base_amt    : uint256,
  quote_amt   : uint256,
  ctx         : Ctx) -> uint256:

  self._INTERNAL()

  user        : address   = tx.origin
  total_supply: uint256   = ERC20(lp_token).totalSupply()
  pool        : PoolState = self.POOLS.lookup(id)
  lp_amt      : uint256   = self.POOLS.calc_mint(id, base_amt, quote_amt, total_supply, ctx) #@audit-issue more lp will be minted in case usdt is FoT later

  assert pool.base_token  == base_token , ERR_PRECONDITIONS
  assert pool.quote_token == quote_token, ERR_PRECONDITIONS
  assert pool.lp_token    == lp_token   , ERR_PRECONDITIONS
  assert base_amt > 0 or quote_amt > 0  , ERR_PRECONDITIONS
  assert lp_amt > 0                     , ERR_PRECONDITIONS

  assert ERC20(base_token).transferFrom(user, self, base_amt, default_return_value=True), "ERR_ERC20"
  assert ERC20(quote_token).transferFrom(user, self, quote_amt, default_return_value=True), "ERR_ERC20" #@audit-issue will transfer less in case USDT implements fee-on transfer
  assert ERC20Plus(lp_token).mint(user, lp_amt), "ERR_ERC20"

  self.POOLS.mint(id, base_amt, quote_amt) #@audit reserves will be increased by incorrect amount
  self.FEES.update(id)

  self.INVARIANTS(id, base_token, quote_token)

  log Mint(user, ctx, pool, total_supply, lp_amt, base_amt, quote_amt)

  return lp_amt
```
 USDT  is in a category of  ERC20   tokens have the possibility of adding fees in the future. Based on this, if it implements fee-on transfer, the amount transfered in the line `assert ERC20(quote_token).transferFrom(user, self, quote_amt, default_return_value=True), "ERR_ERC20"` will be less than actual amount, which  will lead to breaking an invariant defined  in [self.INVARIANTS](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L125C1-L133C68). Let's take a look at this function:
```python
@internal
def INVARIANTS(id: uint256, base_token: address, quote_token: address):
  pool         : PoolState = self.POOLS.lookup(id)
  base_balance : uint256   = ERC20(base_token).balanceOf(self)
  quote_balance: uint256   = ERC20(quote_token).balanceOf(self)
  assert base_balance  >= (pool.base_reserves  + pool.base_collateral),  ERR_INVARIANTS
  assert quote_balance >= (pool.quote_reserves + pool.quote_collateral), ERR_INVARIANTS #@audit-issue this will revert
  assert pool.base_reserves  >= pool.base_interest,  ERR_INVARIANTS
  assert pool.quote_reserves >= pool.quote_interest, ERR_INVARIANTS
```
The line `assert quote_balance >= (pool.quote_reserves + pool.quote_collateral), ERR_INVARIANTS` will revert. 
Suppose the user transfers 100 USDT, and there's a 1% fee. The pool will only receive 99 USDT. The state variable quote_reserves will be updated as if the pool received 100 USDT, but in reality, the pool contract balance only holds 99 USDT. Therefore mint() will not be functioning as expected. 
**Second Scenario:** 
Consider a pool is created with one of the pair token being USDT when it has no fee-on transfer. The pool has been working with many users and after a while USDT has implemented fee-on transfer. Let's see what happens when users wants to withdraw their liquidity. The [burn](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L191) in core.vy will be called:
```python
@external
def burn(
  id          : uint256,
  base_token  : address,
  quote_token : address,
  lp_token    : address,
  lp_amt      : uint256,
  ctx         : Ctx) -> Tokens:

  self._INTERNAL()

  user        : address   = tx.origin
  total_supply: uint256   = ERC20(lp_token).totalSupply()
  pool        : PoolState = self.POOLS.lookup(id)
  amts        : Tokens    = self.POOLS.calc_burn(id, lp_amt, total_supply, ctx)
  base_amt    : uint256   = amts.base
  quote_amt   : uint256   = amts.quote

  assert pool.base_token  == base_token , ERR_PRECONDITIONS
  assert pool.quote_token == quote_token, ERR_PRECONDITIONS
  assert pool.lp_token    == lp_token   , ERR_PRECONDITIONS
  assert base_amt > 0 or quote_amt > 0  , ERR_PRECONDITIONS
  assert lp_amt > 0                     , ERR_PRECONDITIONS

  assert ERC20(base_token).transfer(user, base_amt, default_return_value=True), "ERR_ERC20" #@audit balance will be decreased less than expected due the fee
  assert ERC20(quote_token).transfer(user, quote_amt, default_return_value=True), "ERR_ERC20"
  assert ERC20Plus(lp_token).burn(user, lp_amt), "ERR_ERC20"

  self.POOLS.burn(id, base_amt, quote_amt) #@reserves will be decreased by quote_amt
  self.FEES.update(id)

  self.INVARIANTS(id, base_token, quote_token)

  log Burn(user, ctx, pool, total_supply, lp_amt, base_amt, quote_amt)

  return amts
```
The check `quote_balance >= (pool.quote_reserves + pool.quote_collateral), ERR_INVARIANTS.` in `self.INVARIANTS()` will be reverted due the insufficient balance and making impossible for users to withdraw their liquidity.
For simplicity and to see the flow more clearly, the same example mentioned above can be given. Assume a user is withdrawing liquidity, and based on their LP share, the protocol determines they are entitled to withdraw 100 USDT. The protocol’s internal state shows `quote_reserves = 100 USDT`, which reflects the total USDT held by the contract for this pool. The contract calls `ERC20(quote_token).transfer(user, quote_amt)` where quote_amt = 100 USDT. If USDT applies a 1% fee, the contract sends 100 USDT to the transfer function, but the user only receives 99 USDT, and 1 USDT is  taken as a fee. Now, the contract’s USDT balance is 99 USDT due the deducted fee while the protocol’s internal quote_reserves still expects 100 USDT. Therefore the invariant mentioned above will revert.
## Impact
For the first case, considering each pool has unique pair of token, another quote token can not be used and the core functionality of the pool will be broken, hence making the pool useless.  
For the second case, users funds may potentially stuck in the contract.
## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L155
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/core.vy#L125C1-L133C68

## Tool used
Manual Review
## Recommendation
I would recommend check balance before/after of quote token and do the necessary implementation based on the actual deposit/withdrawal amount.

**Comment by IWildSniperI** [comment]
Escalate

On behalf of issue writer

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> On behalf of issue writer

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by oxwhite** [comment]
USDT was in question in terms of scope from the beginning  of the contests and asked by a bunch of the watsons in Discord channel. That can be confirmed by the Discord message. Finally it has been confirmed that it is in scope. Here is the prove:
![Ekran görüntüsü 2024-09-11 213535](https://github.com/user-attachments/assets/1faaa3cd-66e7-4157-b691-f5761eb6bee3)
https://discord.com/channels/812037309376495636/1279093303719100426/1282070002689638433. When this is the case,  in the second scenario mentioned in the report, the impact is high. Because if there is running pool with quote token being USDT, and USDT has implemented fee, due the insufficient balance(fee-deducted), withdraw function will revert. Here is a very similar bug accepted in the previous contest on Sherlock: https://solodit.xyz/issues/m-04-fee-on-transfer-underlying-can-cause-problems-code4rena-swivel-swivel-contest-git. 
Also There are many other similar issues that are accepted in different contests: Here are 2 more examples:https://solodit.xyz/issues/m-17-auction-collateraltoken-wont-work-if-token-is-fee-on-transfer-token-code4rena-malt-finance-malt-finance-contest-git
https://solodit.xyz/issues/m-07-vault-cant-receive-deposits-if-underlying-token-charges-fees-on-transfer-code4rena-sandclock-sandclock-contest-git
Considering it is obviously expressed that USDT in scope. This should be valid.

**Comment by spacegliderrrr** [comment]
Issue above is invalid. [USDT](https://explorer.gobob.xyz/token/0x05D032ac25d322df992303dCa074EE7392C117b9?tab=contract) on BOB does not have a fee-switch.

**Comment by oxwhite** [comment]
> Issue above is invalid. [USDT](https://explorer.gobob.xyz/token/0x05D032ac25d322df992303dCa074EE7392C117b9?tab=contract) on BOB does not have a fee-switch.

Thanks for pointing out. Even if ı checked some weird features of USDT, I  missed checking this one.

**Comment by WangSecurity** [comment]
Planning to reject the escalation and leave the issue as it is since the fee cannot be turned on on USDT.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [IWildSniperI](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/70/#issuecomment-2344395141): rejected
