### ISSUE TITLE
Yashar - A USDC blacklisted address can lock an amount of quote tokens in the pool

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-velar-artha-judging#71]
Yashar

High

# A USDC blacklisted address can lock an amount of quote tokens in the pool

## Summary
A USDC blacklisted address can lock an amount of quote tokens in the pool by opening a short position. Since this position can't be closed or liquidated, and the protocol always maintains the amount needed to close this position, an equivalent amount of quote tokens will remain locked up indefinitely.

## Vulnerability Detail
As described in the comments [here](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/pools.vy#L198-L200), the protocol will always hold a sufficient number of reserve tokens to pay out any open positions, which are locked at all times:
```python
# Burning LP tokens is not always possible, since pools are fully-backed and
# a sufficient number of reserve tokens to pay out any open positions is locked
# at all times (all positions are guaranteed to close eventually due to fees).
```

Given that the quote tokens in the pools are stablecoins like USDT or USDC, and the sponsor has confirmed that the protocol will use these tokens as quotes for their pools, if a USDC blacklisted address opens a short position on a BTC/USDC pool, this position will not close. When the protocol attempts to transfer the quote token to the user, the transaction will revert. Consequently, the protocol will always hold a reserve of quote tokens, which are LP funds, to ensure this position eventually closes, locking these funds in the contract. This situation can occur in two scenarios:
1. A blacklisted USDC address maliciously opens a short position to lock up LP funds.
2. A user who opened a short position before being blacklisted by USDC cannot close the position.

The USDC contract on BOB, which has a blacklisting mechanism, can be found [here](https://explorer.gobob.xyz/address/0x27D58e4510a3963Abc70BCe554aeAC60846998ab?tab=contract).

## Impact

LP funds will be locked up in the contract.

## Code Snippet

https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/pools.vy#L198-L200

## Tool used

Manual Review

## Recommendation
1. Allow the user to define an address for the receiver in the case where the user is blacklisted after opening a short position.
2. Use a try/catch block while transferring quote tokens to the user during liquidation.
```diff
@external
def liquidate(
  id         : uint256,
  base_token : address,
  quote_token: address,
  position_id: uint256,
  ctx        : Ctx) -> PositionValue:

  self._INTERNAL()

  # identical to close()
  user    : address       = tx.origin #liquidator
  pool    : PoolState     = self.POOLS.lookup(id)
  position: PositionState = self.POSITIONS.lookup(position_id)

  assert pool.base_token  == base_token                  , ERR_PRECONDITIONS
  assert pool.quote_token == quote_token                 , ERR_PRECONDITIONS
  assert id == position.pool                             , ERR_PRECONDITIONS
  assert self.POSITIONS.is_liquidatable(position_id, ctx), ERR_PRECONDITIONS

  value    : PositionValue = self.POSITIONS.close(position_id, ctx)
  base_amt : uint256       = self.MATH.eval(0, value.deltas.base_transfer)
  quote_amt: uint256       = self.MATH.eval(0, value.deltas.quote_transfer)
  self.POOLS.close(id, value.deltas)
  self.FEES.update(id)

  base_amt_final : Fee = self.PARAMS.liquidation_fees(base_amt)
  quote_amt_final: Fee = self.PARAMS.liquidation_fees(quote_amt)

  # liquidator gets liquidation fee, user gets whatever is left
  if base_amt_final.fee > 0:
    assert ERC20(base_token).transfer(user, base_amt_final.fee, default_return_value=True), "ERR_ERC20"
  if quote_amt_final.fee > 0:
    assert ERC20(quote_token).transfer(user, quote_amt_final.fee, default_return_value=True), "ERR_ERC20"
- if base_amt_final.remaining > 0:
-   assert ERC20(base_token).transfer(position.user, base_amt_final.remaining, default_return_value=True), "ERR_ERC20"
- if quote_amt_final.remaining > 0:
-   assert ERC20(quote_token).transfer(position.user, quote_amt_final.remaining, default_return_value=True), "ERR_ERC20"
+
+ try:
+     if base_amt_final.remaining > 0:
+         ERC20(base_token).transfer(position.user, base_amt_final.remaining, default_return_value=True)
+ except Exception:
+     pass
+
+ try:
+     if quote_amt_final.remaining > 0:
+       ERC20(quote_token).transfer(position.user, quote_amt_final.remaining, default_return_value=True)
+ except Exception:
+     pass
      
  self.INVARIANTS(id, base_token, quote_token)

  log Liquidate(user, ctx, pool, value)
  return value
```

**Comment by yashar0x** [comment]
escalate

as discussed in the Discord PT, the sponsor has indicated that they may use USDC as the quote token (they can confirm this)

**Comment by spacegliderrrr** [comment]
Issue should remain invalid. As per the readme, no weird tokens will be used (which includes USDC).

**Comment by yashar0x** [comment]
@spacegliderrrr USDT is also a weird token but according to [this confirmation](https://discord.com/channels/812037309376495636/1279093303719100426/1282070002689638433) and the comments in the codebase it'll be used by the protocol

USDC will also be used by the protocol, as confirmed by the sponsor in the PT. however, since the sponsor didn’t review the findings before the preliminary results, the lead judge invalidated this issue!![image](https://github.com/user-attachments/assets/a3891f3b-f3fb-4527-98c3-a0ad3e2eb30a)

**Comment by msheikhattari** [comment]
Duplicate of #136

**Comment by yashar0x** [comment]
@msheikhattari this finding is not a dup of #136
that report is wrong since USDT on BOB doesn't have a blacklisting mechanism at all
just USDC has blacklisting mechanism

**Comment by WangSecurity** [comment]
Based on the README, only standard tokens + USDT will be used in the protocol. Hence, USDC is out-of-scope regardless of the information from the sponsor or code comments, because they conflict README.

Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yashar0x](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/71/#issuecomment-2344315943): rejected
