### ISSUE TITLE
KupiaSec - Improper calculation of utilization ratio

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-velar-artha-judging#78]
KupiaSec

Medium

# Improper calculation of utilization ratio

## Summary
Utilization ratio calculation is executed in improper way that might lead to DoS.

## Vulnerability Detail
```vyper
def utilization(reserves: uint256, interest: uint256) -> uint256:
    """
    Reserve utilization in percent (rounded down).
    """
    return 0 if (reserves == 0 or interest == 0) else (interest / (reserves / 100))
```

Here's the code snippet of `utilization` function that calculates utilization ration based on `interest` and `reserves` and returns as percentage between 0 and 100.

As shown in the code snippet, it calculates `reserves / 100` first and then divides the `interest`.
This means that the transaction reverts when `reserves` is between 1 and 99 because of division by zero.

The `utilization` function is called whenever there's an action in the protocol, e.g. opening and closing positions.
So as a result, when `reserves` is less than 100, the protocol does not work until someone adds LP to the pool, even though this can be rare cases in usual.

## Impact
DoS of protocol because if incorrect calculation.
Another impact is the description says it does rounding down, but it will round-up in some cases.

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/params.vy#L59-L63

## Tool used
Manual Review

## Recommendation
The calculation should be modified as follows:

```diff
def utilization(reserves: uint256, interest: uint256) -> uint256:
    """
    Reserve utilization in percent (rounded down).
    """
-   return 0 if (reserves == 0 or interest == 0) else (interest / (reserves / 100))
+   return 0 if (reserves == 0 or interest == 0) else (interest * 100 / reserves)
```

**Comment by KupiaSecAdmin** [comment]
Escalate

Information required for this issue to be rejected.

**Comment by msheikhattari** [comment]
The likelihood and impact of this attack are both low which is why this was invalidated from medium severity. Duplicate of #87 which was also invalidated.

**Comment by WangSecurity** [comment]
To clarify, reserves and interest are token amounts and in that case, interest and reserves of 1 ETH, would be 1e18? Or there's a different precision?

**Comment by KupiaSecAdmin** [comment]
@WangSecurity - Same decimal with tokens, so in case of ETH, it will be 18 decimals.

**Comment by WangSecurity** [comment]
This is a duplicate of #87, and the discussion there is already longer, so I'll keep the main discussion there. If #87 escalation is accepted and issue is valid, this escalation will also be accepted and the issue will be validated. If #87 escalation is rejected, this escalation will be rejected as well.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

> *Note: see discussion under #87*

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/78/#issuecomment-2344253085): rejected
