### ISSUE TITLE
KupiaSec - Protocol actions might revert because of tokens that revert on zero value transfer

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-velar-artha-judging#80]
KupiaSec

Medium

# Protocol actions might revert because of tokens that revert on zero value transfer

## Summary
Some actions in the protocol transfer tokens without checking the amount to transfer, which might lead to unexpected revert issue when either base/quote token reverts on zero value transfer.

## Vulnerability Detail
```vyper
@external
def mint(
  ...
  assert ERC20(base_token).transferFrom(user, self, base_amt, default_return_value=True), "ERR_ERC20"
  assert ERC20(quote_token).transferFrom(user, self, quote_amt, default_return_value=True), "ERR_ERC20"
  ...
```
In some actions like `mint`, the protocol transfers base and quote assets from the user to the pool by calling `transferFrom`.
However, it does not check if `base_amt` or `quote_amt` is zero. Some ERC20 tokens revert when transferring zero value between accounts.

If those tokens are integrated with Verla protocol, the protocol stops working.

## Impact
DoS of the protocol when base or quote asset token reverts on zero value transfer.

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/core.vy#L177-L178
https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/core.vy#L215-L216

## Tool used
Manual Review

## Recommendation
It should check the token amount to transfer before it actually calls `transfer` or `transferFrom`.

**Comment by KupiaSecAdmin** [comment]
Escalate

Information required for this issue to be rejected. Thanks.

**Comment by spacegliderrrr** [comment]
Non-issue as tokens which revert on zero-value transfers are considered weird. As per the readme, no weird tokens are supported.

**Comment by WangSecurity** [comment]
The above comment is correct; no such tokens are in-scope. Planning to reject the escalation and leave the issue as it is.

**Comment by KupiaSecAdmin** [comment]
Agree with rejecting the issue since these tokens are out-of-scope. Thanks @WangSecurity @spacegliderrrr for clarification.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/80/#issuecomment-2344258550): rejected
