### ISSUE TITLE
KupiaSec - Missing `default_return_value` for some token transfers

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-velar-artha-judging#81]
KupiaSec

Medium

# Missing `default_return_value` for some token transfers

## Summary
`default_return_value` is missing in some transfer actions, which might lead to revert when base or quote token is an ERC20 that does not return boolean after transfer, e.g. USDT

## Vulnerability Detail
Some ERC20 tokens including USDT does not return a boolean value in `transfer` or `transferFrom` external functions.
For this reason, `default_return_value` is used across the protocol not to revert when these tokens are integrated.

```vyper
@external
def open(
  ...

  if long: assert ERC20(quote_token).transferFrom(user, self, collateral0), "ERR_ERC20"
  else   : assert ERC20(base_token).transferFrom(user, self, collateral0),  "ERR_ERC20"

  # transfer protocol fees to separate contract
  if long: assert ERC20(quote_token).transfer(self.COLLECTOR, fee), "ERR_ERC20"
  else   : assert ERC20(base_token).transfer(self.COLLECTOR, fee),  "ERR_ERC20"

  ...
```

However, in `open` function, setting `default_return_value` is missing, which leads to revert when this kind of token is integrated.

## Impact
Users can not open positions when tokens like USDT are integrated with Verla protocol.

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/core.vy#L253-L258

## Tool used
Manual Review

## Recommendation
`default_return_value` attribute has to be used in `open` function as well, shown below:

``````diff
@external
def open(
  ...

- if long: assert ERC20(quote_token).transferFrom(user, self, collateral0), "ERR_ERC20"
- else   : assert ERC20(base_token).transferFrom(user, self, collateral0),  "ERR_ERC20"
+ if long: assert ERC20(quote_token).transferFrom(user, self, collateral0, default_return_value=True), "ERR_ERC20"
+ else   : assert ERC20(base_token).transferFrom(user, self, collateral0, default_return_value=True),  "ERR_ERC20"

  # transfer protocol fees to separate contract
- if long: assert ERC20(quote_token).transfer(self.COLLECTOR, fee), "ERR_ERC20"
- else   : assert ERC20(base_token).transfer(self.COLLECTOR, fee),  "ERR_ERC20"
+ if long: assert ERC20(quote_token).transfer(self.COLLECTOR, fee, default_return_value=True), "ERR_ERC20"
+ else   : assert ERC20(base_token).transfer(self.COLLECTOR, fee, default_return_value=True),  "ERR_ERC20"

  ...
```

**Comment by KupiaSecAdmin** [comment]
Escalate

Information required for this issue to be rejected. Thanks.

**Comment by JeffCX** [comment]
https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/134 is a duplicate of this issue as well.'

This should be a valid medium

**Comment by sleepriverfish** [comment]
#34 is a duplicate of this issue as well.

**Comment by PseudoArtistHacks** [comment]
#25 is a duplicate of this issue too

**Comment by WangSecurity** [comment]
As I understand, [USDT on Bob](https://explorer.gobob.xyz/token/0x05D032ac25d322df992303dCa074EE7392C117b9?tab=contract) does return a boolean, so this issue will not happen. Planning to reject the escalation and leave the issue as it is.

**Comment by KupiaSecAdmin** [comment]
@WangSecurity - It would be fine with USDT, but base tokens that will be supported might not return a boolean.

**Comment by WangSecurity** [comment]
Based on the README, the protocol only supports standard tokens (without weird traits) and USDT. Missing return value is a weird trait. Hence, this issue is out-of-scope for this contest. The decision remains, reject the escalation and leave the issue as it is.

**Comment by KupiaSecAdmin** [comment]
I think tokens without return value wouldn't be a weird trait, because there many tokens with this trait and that's how `SafeERC20` library is used. Also, it's correctly implemented throughout the protocol but not in the function mentioned in the report.

**Comment by WangSecurity** [comment]
Unfortunately, all traits from [this repo](https://github.com/d-xo/weird-erc20) are considered weird traits (it's also linked in the Sherlock Rules). Missing return value is a weird trait in that repository. Hence, this issue is out-of-scope of this contest. Planning to reject the escalation and leave the issue as it is.

**Comment by KupiaSecAdmin** [comment]
@WangSecurity - Fair enough, agree with invalidating this issue unless others have any counterarguments.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/81/#issuecomment-2344259243): rejected
