### ISSUE TITLE
bughuntoor - User might be unable to close a position if the remaining interest and reserves are a dust amount.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-velar-artha-judging#87]
bughuntoor

High

# User might be unable to close a position if the remaining interest and reserves are a dust amount.

## Summary
User might be unable to close a position if the remaining interest and reserves are a dust amount.

## Vulnerability Detail
At the end of `close`, `fees.UPDATE` is called.

```vyper
  value    : PositionValue = self.POSITIONS.close(position_id, ctx)
  base_amt : uint256       = self.MATH.eval(0, value.deltas.base_transfer)
  quote_amt: uint256       = self.MATH.eval(0, value.deltas.quote_transfer)
  self.POOLS.close(id, value.deltas)
  self.FEES.update(id)
```

The way the function works is that it fetches the previous fee terms, applies them for the time period since then and then calculates the new fee terms. The problem lies in the calculation of the new fee terms and precisely in the utilization calculation

```vyper
def dynamic_fees(pool: PoolState) -> DynFees:
    long_utilization : uint256 = self.utilization(pool.base_reserves, pool.base_interest)
    short_utilization: uint256 = self.utilization(pool.quote_reserves, pool.quote_interest)
```

```vyper
def utilization(reserves: uint256, interest: uint256) -> uint256:
    """
    Reserve utilization in percent (rounded down).
    """
    return 0 if (reserves == 0 or interest == 0) else (interest / (reserves / 100))
```

As we can see, the idea is to calculate a percentage. However, due to the division of `reserves / 100`, if `reserves < 100` , this would round down to 0 and then revert due to division by 0, which would ultimately not allow a user to close their position.

Furthermore, if the user has the only position on one's side (whether that be short or long), LP providers can abuse that to make his position impossible to close.

## Impact
Loss of funds

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/params.vy#L63

## Tool used

Manual Review

## Recommendation
Instead of calculating `(interest / (reserves / 100))`, better use `(interest * 100) / reserves`

**Comment by spacegliderrrr** [comment]
Escalate 

Issue should be validated. It correctly showcases how in an edge case a user may not be able to close their position. Given that closing a position is a time-sensitive operation and user funds are at risk, issue should be Medium severity.

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> Issue should be validated. It correctly showcases how in an edge case a user may not be able to close their position. Given that closing a position is a time-sensitive operation and user funds are at risk, issue should be Medium severity.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by msheikhattari** [comment]
This is only applicable when `interest` and `reserves` are both under 100 wei (since `interest` must never exceed `reserves`), so the funds potentially at stake are extremely low. Additionally the likelihood is very low since it requires a pool to have less than 100 wei in reserves, which would require there to be no real LPs in the pool.

Low likelihood and severity, so this is correctly invalidated from being high.

**Comment by KupiaSecAdmin** [comment]
Regarding impact, it does not impact funds but it prevents users from closing positions which could rebalance LPs.

**Comment by spacegliderrrr** [comment]
Regarding the reserves requirement - it does not require having `reserves < 100`, but rather outstanding reserves to be less than 100. Which would mean that if a user opens a long for position for all but 100 wei of the reserves, they would later not be able to close it. 

> Additionally the likelihood is very low since it requires a pool to have less than 100 wei in reserves, which would require there to be no real LPs in the pool.

Incorrect, as issue can occur if there are even $100k in the pool and user opens a $100k position for all but 100 wei (which could happen due to rounding).

> Regarding impact, it does not impact funds but it prevents users from closing positions 

Not being able to close a perp position does directly impact user's funds. Perps are time-sensitive and not being able to close your position even for a few minutes could have critical impact.

**Comment by msheikhattari** [comment]
> Regarding the reserves requirement - it does not require having reserves < 100, but rather outstanding reserves to be less than 100. Which would mean that if a user opens a long for position for all but 100 wei of the reserves, they would later not be able to close it.

`dynamic_fees` uses the `pool.base_reserves` and `pool.quote_reserves`, which reflect the total amount of LP deposited tokens - these values only change when the LP mints (increasing reserves) or burns (decreasing reserves). It does not reflect outstanding reserves but the total reserves of the pool.

If you are referring to `unlocked_reserves`, which is reserves net of open interest, that is only used to determine how much LPs can burn. It has no impact on users opening or closing positions (aside from an invariants check at the end of each function that ensures unlocked reserves > 0 after each operation - not relevant here).

**Comment by WangSecurity** [comment]
To clarify, as I understand based on the above comment, for this issue to happen, indeed the pool has to have total reserves < 100 wei. But in that scenario, how large could the position be? Can it be any size?

**Comment by msheikhattari** [comment]
Position interest cannot exceed reserves as one of the invariants enforced throughout CORE.vy, therefore the impacted funds is similarly capped at 100wei

**Comment by deadrosesxyz** [comment]
@WangSecurity No, you’re misunderstanding the issue. The reserves BEYOND the position must not exceed 100. 

So if there’s 1 WBTC + 99 wei in reserves and user’s position should pay out 1 WBTC, it will revert and the user will be unable to close it.

**Comment by WangSecurity** [comment]
@deadrosesxyz I think I indeed misunderstood something, but here's how I see it:
The problem is if the `reserve` parameter inside the `utilization` function is <100. But, the `utilization` function is called in the `dynamic_fees` function. We calculate the utilization for long and short positions. Longs use `pool.base_reserves` and `pool.base_interest`, while shorts use the same but in quote token. 

As I understand, `pool.base_reserves` and `pool.base_interest` are the total base reserves and interest of the pool (similar to quote token). Also, I don't see it being decreased when opening a position, i.e. if there are 1 BTC + 99 wei of reserves and you open 1 BTC long, the reserves are decreased to 99 wei, i.e. only outstanding reserves are accounted. Where am I missing that `pool.base_reserves` and `pool.quote_reserves` refer only to the outstanding reserves and not total reserves? (excuse me if it's a silly question, but I actually don't see it).

**Comment by WangSecurity** [comment]
Bumping @deadrosesxyz and @KupiaSecAdmin to clarify.

**Comment by deadrosesxyz** [comment]
> if there are 1 BTC + 99 wei of reserves and you open 1 BTC long, the reserves are decreased to 99 wei, i.e. only outstanding reserves are accounted. 

This is wrong. If there's 1 BTC + 99 of reserves, and you open a long, the reserves do not [change](https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/pools.vy#L248). The reserves do change upon closing that position. So when you close the position for 1 BTC, then the remaining reserves will be 99 wei as mentioned above.

**Comment by pashap9990** [comment]
invalid
let's assume
pool_reserve =  1 BTC + 99
BTC price = $50,000
leverage = 1x
collateral = 50,000 usdt
after opening position
<ins>base_interest = 1 BTC</ins>

then user decide to close his position[price = $50,000]
pool_reserve = 99 wei
<ins>base_interest = 0</ins>
long_utilization = 0
```vyper
def close(id: uint256, d: Deltas) -> PoolState:
  """
  Apply transfers resulting from a position close to pool state.
  """
  self._INTERNAL()
  ps: PoolState = Pools(self).lookup(id)
return self.insert(PoolState({
    id               : ps.id,
    symbol           : ps.symbol,
    base_token       : ps.base_token,
    quote_token      : ps.quote_token,
    lp_token         : ps.lp_token,
    base_reserves    : self.MATH.eval(ps.base_reserves,    d.base_reserves),
    quote_reserves   : self.MATH.eval(ps.quote_reserves,   d.quote_reserves),
@>>>>    base_interest    : self.MATH.eval(ps.base_interest,    d.base_interest),
    quote_interest   : self.MATH.eval(ps.quote_interest,   d.quote_interest),
    base_collateral  : self.MATH.eval(ps.base_collateral,  d.base_collateral),
    quote_collateral : self.MATH.eval(ps.quote_collateral, d.quote_collateral),
  }))
```


```vyper
def util(reserves: uint256, interest: uint256) -> uint256:
  return 0 
@>>>  if (reserves == 0 or interest == 0) 
  else (interest / (reserves / 100))
```

**Comment by WangSecurity** [comment]
Hmm, so if it's the only open position, then the interest is updated before updating the fees, i.e. [`self.POOLS.close(id, value. deltas)`](https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/core.vy#L293) where interest is decreased to 0 is called before [`self.FEES.update(id)`](https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/core.vy#L) utilisation is calculated. Hence, there would be no revert. But is there a scenario where interest can remain non-zero in this case? For example, there's another position, but that should be 99 wei or less?

**Comment by pashap9990** [comment]
> Hmm, so if it's the only open position, then the interest is updated before updating the fees, i.e. [`self.POOLS.close(id, value. deltas)`](https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/core.vy#L293) where interest is decreased to 0 is called before [`self.FEES.update(id)`](https://github.com/sherlock-audit/2024-08-velar-artha/blob/18ef2d8dc0162aca79bd71710f08a3c18c94a36e/gl-sherlock/contracts/core.vy#L) utilisation is calculated. Hence, there would be no revert. But is there a scenario where interest can remain non-zero in this case? For example, there's another position, but that should be 99 wei or less?

Yes,position's size should be 99 wei or less because users cannot open a position with interest bigger than the pool's reserve, also likelihood is very rare to open a position with 99 wei base or quote interest because admin manages positions with set min collateral
```vyper
def is_legal_position(pool: PoolState, position: PositionState) -> bool:
   @>>>>>  min_size: bool = position.collateral >= (self.PARAMS.MIN_LONG_COLLATERAL if position.long else
                                             self.PARAMS.MIN_SHORT_COLLATERAL)
    # Max size limits are not really enforceable since users can just
    # open multiple identical positions.
    # This can be used as a pause button (set to zero to prevent new
    # positions from being opened).
    max_size: bool = position.collateral <= (self.PARAMS.MAX_LONG_COLLATERAL if position.long else
                                             self.PARAMS.MAX_SHORT_COLLATERAL)
    min_leverage: bool = position.leverage >= (self.PARAMS.MIN_LONG_LEVERAGE if position.long else
                                               self.PARAMS.MIN_SHORT_LEVERAGE)
    max_leverage: bool = position.leverage <= (self.PARAMS.MAX_LONG_LEVERAGE if position.long else
                                               self.PARAMS.MAX_SHORT_LEVERAGE)
    return min_size and max_size and min_leverage and max_leverage
```

**Comment by WangSecurity** [comment]
However, the collateral can decrease and even reach 0 in some cases (as shown in other reports). As I understand, this check (`min_size`) is done only when opening positions. However, after that, the collateral can decrease to less than 99 wei. Hence, if there are two positions opened and one is very low on collateral, then this situation is possible. Is it correct?

**Comment by pashap9990** [comment]
yes, you're right and remaining collateral will be decrease but that doesn't have effect here 
```
def util(reserves: uint256, interest: uint256) -> uint256:
  return 0 
if (reserves == 0 or interest == 0) 
@>>>  else (interest / (reserves / 100))
 ```
 interest and reserve are important here

**Comment by WangSecurity** [comment]
To clarify, for example, if the position size is 100 wei, the user opens a position, and it decreases below 100. Then there would be no issue because the interest and reserves would still exceed 100?

**Comment by pashap9990** [comment]
yes

**Comment by WangSecurity** [comment]
Thank you for explaining. In that sense, I agree that this issue won't happen. Planning to reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [spacegliderrrr](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/87/#issuecomment-2344500870): rejected
