### ISSUE TITLE
bughuntoor - `base_to_quote` wrongly assume quote always has less decimals

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-velar-artha-judging#91]
bughuntoor

High

# `base_to_quote` wrongly assume quote always has less decimals

## Summary
`base_to_quote` wrongly assume quote always has less decimals

## Vulnerability Detail
Let's look at the code of `base_to_quote`

```vyper
def base_to_quote(tokens: uint256, ctx: Ctx) -> uint256:                                # price is in quote decimals 
  lifted : Tokens  = self.lift(Tokens({base: tokens, quote: ctx.price}), ctx)           # get scaled to whichever has more decimals 
  amt0   : uint256 = self.to_amount(lifted.quote, lifted.base, self.one(ctx))           # amount gets calculated in whichever has more decimals 
  lowered: Tokens  = self.lower(Tokens({base: 0, quote: amt0}), ctx)                    # amount gets refactored to whichever has less decimals -> will be wrong if that's base
  return lowered.quote
```

In the input params, `tokens` is in base decimals and the price is in `quote` decimals.
As we can see, the first line scales to whichever has more decimals.
Then the amount is calculated, once again scaled in whichever has more decimals.
Then it is lowered to whichever has lower decimals.

It basically makes an assumption that the quote always has less decimals, which is not the case. If the pair is `WBTC/DAI` for example, it would be completely broken and allow for draining all assets.

## Impact
Loss of funds.

## Code Snippet
https://github.com/sherlock-audit/2024-08-velar-artha/blob/main/gl-sherlock/contracts/math.vy#L73

## Tool used

Manual Review

## Recommendation
Do proper decimals scaling

**Comment by spacegliderrrr** [comment]
Escalate. 

Issue should be of High severity as it completely breaks the whole pricing of both tokens. It would allow draining all funds within the contract.

**Comment by sherlock-admin3** [comment]
> Escalate. 
> 
> Issue should be of High severity as it completely breaks the whole pricing of both tokens. It would allow draining all funds within the contract.

You've deleted an escalation for this issue.

**Comment by msheikhattari** [comment]
This issue is invalid.

To see why let's run through the example you provided of WBTC/DAI (8 decimals base, 18 decimals quote)

Let tokens = 1e8 and ctx.price = 50_000e18 (same precision as quote - 18 decimals)
Note bd = 8, qd = 18

```vyper
lifted = Tokens{base: 1e8 * 10**10, quote: 50_000e18}
amt0 = (1e18 * 50_000e18) / 10**18
lowered = Tokens{base: 0, quote: amt0}
```

So 1 WBTC is converted to 50_000e18 DAI, as expected.

**Comment by spacegliderrrr** [comment]
Statement above is correct.

**Comment by KupiaSecAdmin** [comment]
Escalate

Adding escalation label again for invalidation.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Adding escalation label again for invalidation.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by pashap9990** [comment]
definitely invalid
```python
def test_base_to_quote(math):
     ...
    assert math.base_to_quote(100_000_000, ctx(500_000_000, 6, 8)) == 50_000_000_000
```

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept it and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-08-velar-artha-judging/issues/91/#issuecomment-2345151448): accepted
